apiVersion: v1
kind: Service
metadata:
  name: cloud-service
spec:
  type: NodePort  # Change to NodePort for external access
  selector:
    app: cloud-storage
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002  # Optional: Specify a NodePort (30000-32767) for external access
