apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-app  # Replace with your actual pod label
  ports:
    - port: 5000         # The port your Flask app is running on
      targetPort: 5000    # The port on the pod
      nodePort: 30000     # Port you want to expose on the node
