apiVersion: v1
kind: Service
metadata:
  name: fog-service-2
spec:
  type: NodePort
  selector:
    app: fog-processor-2
  ports:
    - protocol: TCP
      port: 5011
      targetPort: 5011
      nodePort: 30011
