apiVersion: apps/v1
kind: Deployment
metadata:
  name: fog-processor-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fog-processor-3
  template:
    metadata:
      labels:
        app: fog-processor-3
    spec:
      containers:
      - name: opencv-processor-3
        image: dabblu/fog_image_3
        ports:
        - containerPort: 5021
      # Uncomment and configure if needed
      # nodeSelector:
      #   role: fog
