apiVersion: v1
kind: Service
metadata:
  name: fog-service-3
spec:
  type: NodePort
  selector:
    app: fog-processor-3
  ports:
    - protocol: TCP
      port: 5021
      targetPort: 5021
      nodePort: 30021
