# edge_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: edge-service
spec:
  type: NodePort
  selector:
    app: edge-camera
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
